# Configuración para la conexión de la base de datos con Spring Boot
# Conexión a PostgresSQL

# AÑADIR ESTO EN CASO DE USAR JSP
# spring.mvc.view.prefix=/WEB-INF/view/
#spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://localhost:5432/urban_pulse_db
spring.datasource.username=admin
spring.datasource.password=database
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración lenguaje UTF-8
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true
spring.messages.encoding=UTF-8

spring.jpa.hibernate.ddl-auto=validate

# Dialecto de base de datos
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostrar consultas SQL formateadas en los logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true